FROM docker.io/mdiblbiocore/samap:latest

# Copy scripts into the container's bin directory
COPY scripts/log_utils.py /usr/local/bin/log_utils.py
COPY scripts/preprocess_seurat_object.R /usr/local/bin/preprocess_seurat_object.R
COPY scripts/preprocess_anndata_object.py /usr/local/bin/preprocess_anndata_object.py
COPY scripts/load_sams.py /usr/local/bin/load_sams.py
COPY scripts/build_samap.py /usr/local/bin/build_samap.py
COPY scripts/run_samap.py /usr/local/bin/run_samap.py
COPY scripts/visualize_samap.py /usr/local/bin/visualize_samap.py
# Make sure it’s executable
RUN ls -l /usr/local/bin

RUN chmod +x /usr/local/bin/preprocess_seurat_object.R
RUN chmod +x /usr/local/bin/preprocess_anndata_object.py
RUN chmod +x /usr/local/bin/load_sams.py
RUN chmod +x /usr/local/bin/build_samap.py
RUN chmod +x /usr/local/bin/run_samap.py
RUN chmod +x /usr/local/bin/visualize_samap.py

# Load the custom patch to fix the analysis module
COPY patches/analysis.py /root/miniconda/lib/python3.8/site-packages/samap/analysis.py

WORKDIR /workspace
