FROM docker.io/avianalter/samap:latest
# Copy scripts into the container's bin directory
COPY scripts/log_utils.py scripts/preprocess_seurat_object.R scripts/preprocess_anndata_object.py scripts/load_sams.py scripts/build_samap.py scripts/run_samap.py scripts/visualize_samap.py /usr/local/bin/
# Make sure it’s executable
RUN chmod -R +x /usr/local/bin/*

# Load the custom patch to fix the analysis module
COPY patches/analysis.py /root/miniconda/lib/python3.8/site-packages/samap/analysis.py
WORKDIR /workspace
