FROM docker.io/staphb/blast:latest

# Copy scripts into the container's bin directory
COPY scripts/update_sample_sheet.sh /usr/local/bin/update_sample_sheet.sh
# Make sure it’s executable
RUN chmod +x /usr/local/bin/update_sample_sheet.sh

WORKDIR /workspace