#!/usr/env/bin nextflow

/*
 *  PIPELINE: main.nf
 *
 *  Description:
 *      SAMap-based cross-species transcriptome mapping pipeline.
 *      Performs preprocessing of input metadata, reciprocal BLAST between
 *      species, SAMap alignment, and visualization of results.
 *
 *  Inputs:
 *      - data/transcriptomes/*.fasta      Input transcriptome FASTA files
 *      - data/*.h5ad                      Precomputed AnnData files
 *      - sample_sheet.csv                 Sample metadata sheet
 *
 *  Workflow Overview:
 *      1. Preprocess sample sheet to classify inputs and assign IDs
 *      2. Generate all unordered species pairs
 *      3. Run reciprocal BLAST on each species pair
 *      4. Build a SAMap object
 *      5. Run SAMap on each BLAST result
 *      6. Visualize SAMap alignment and write results
 *
 *  Parameters:
 *      --run_id        Run ID provided by user. If none is provided a timestamp is used. Default: null
 *      --sample_sheet  Path to the sample sheet provided by user. Default: 'sample_sheet.csv'
 *      --maps_dir      Path to a directory containing precomputed BLAST maps if any are provided. 
 *                      Any value other than null will skip the BLAST module. Default: null
 *      --outdir   The directory all where all results will be stored. Default: '.'
 *
 *  Outputs:
 *      - results_dir/run_id/sample_sheet.csv       Updated metadata with type and ID
 *      - results_dir/run_id/maps/                  Reciprocal BLAST outputs per sample pair
 *      - results_dir/run_id/samap_objects/         Pickled SAMap object (Python)
 *      - results_dir/run_id/plots/chord.html       Chord plot
 *      - results_dir/run_id/plots/sankey.html      Mapping Sankey diagram
 *      - results_dir/run_id/plots/scatter.png      Gene mapping scatter plot
 *      - results_dir/run_id/csv/hms.csv            Highest mapping scores (HMS) matrix
 *      - results_dir/run_id/csv/pms.csv            Pairwise mapping scores (PMS) matrix
 *      - results_dir/run_id/logs/*.log             Logfiles generated by the modules.
 *
 *  Author:     Markus Sujansky, Ryan Sonderman
 *  Created:    2025-06-12
 *  Last Modified: 2025-09-10
 *  Version:    1.0.2
 */

// Import the required modules 
include { RUN_BLAST_PAIR } from './modules/run_blast_pair.nf'
include { validateParameters; paramsHelp; samplesheetToList } from 'plugin/nf-schema'

workflow {
    // Generate run ID unless one is provided
    run_id = params.run_id ?: "${new Date().format('yyyyMMdd_HHmmss')}"
    run_id_ch = Channel.value(run_id)

    // Stage static input files
    sample_sheet    = Channel.fromPath(params.sample_sheet)

    // Validation of necessary files
    if (!new File(params.sample_sheet).exists()) {
        error "Missing required file: sample sheet '${params.sample_sheet}'"
    }
    
    // Reformat Sample_Sheet
    sample_sheet
        .map { file -> 
            def list = samplesheetToList(file.toString(), "./nf-samap/assets/schema_input.json")
            return list
        }
        .flatten()
        .collate(2)
        .set { ch_samples }

 
     // Generate unique unordered sample pairs
    pairs_channel = ch_samples
        .combine(ch_samples)
        .filter { a, b, c, d -> a.id < c.id }

    pairs_channel.view()

        RUN_BLAST_PAIR(
            run_id_ch,
            pairs_channel.map{[it[0], it[2], it[1], it[3]]}
        )
        // Set path to maps from BLAST results
    maps_dir = RUN_BLAST_PAIR.out.maps
} 
